import { apiConfig } from './apiConfig';

const API_URL = 'https://api.linkedin.com/v2';

function getHeaders() {
  return {
    Authorization: `Bearer ${apiConfig.getKey('linkedin_access_token')}`,
    'Content-Type': 'application/json',
    'X-Restli-Protocol-Version': '2.0.0',
  };
}

export async function postToLinkedIn(
  text: string,
  visibility: 'PUBLIC' | 'CONNECTIONS' = 'PUBLIC'
) {
  if (!apiConfig.hasKey('linkedin_access_token')) {
    return {
      success: false,
      error:
        'LinkedIn access token not configured. Go to Settings → API Keys to add it.',
    };
  }

  try {
    const response = await fetch(`${API_URL}/ugcPosts`, {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify({
        author: `urn:li:person:${apiConfig.getKey('linkedin_person_id')}`,
        lifecycleState: 'PUBLISHED',
        specificContent: {
          'com.linkedin.ugc.ShareContent': {
            shareCommentary: { text },
            shareMediaCategory: 'NONE',
          },
        },
        visibility: {
          'com.linkedin.ugc.MemberNetworkVisibility': visibility,
        },
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      return {
        success: false,
        error: error.message || `Error: ${response.status}`,
      };
    }

    const data = await response.json();
    return {
      success: true,
      postId: data.id,
      url: `https://www.linkedin.com/feed/update/${data.id}`,
    };
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Network error',
    };
  }
}

export async function postToLinkedInWithImage(
  text: string,
  imageUrl: string,
  visibility: 'PUBLIC' | 'CONNECTIONS' = 'PUBLIC'
) {
  if (!apiConfig.hasKey('linkedin_access_token')) {
    return {
      success: false,
      error: 'LinkedIn access token not configured.',
    };
  }

  try {
    // Step 1: Register image upload
    const registerResponse = await fetch(`${API_URL}/assets?action=registerUpload`, {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify({
        registerUploadRequest: {
          recipes: ['urn:li:digitalmediaRecipe:feedshare-image'],
          owner: `urn:li:person:${apiConfig.getKey('linkedin_person_id')}`,
          serviceRelationships: [
            {
              relationshipType: 'OWNER',
              identifier: 'urn:li:userGeneratedContent',
            },
          ],
        },
      }),
    });

    if (!registerResponse.ok) {
      return {
        success: false,
        error: 'Failed to register image upload',
      };
    }

    const uploadData = await registerResponse.json();
    const uploadUrl = uploadData.value.uploadMechanism['com.linkedin.digitalmedia.uploading.MediaUploadHttpRequest'].uploadUrl;
    const asset = uploadData.value.asset;

    // Step 2: Upload image
    const imageResponse = await fetch(imageUrl);
    const imageBlob = await imageResponse.blob();

    await fetch(uploadUrl, {
      method: 'PUT',
      body: imageBlob,
    });

    // Step 3: Create post with image
    const response = await fetch(`${API_URL}/ugcPosts`, {
      method: 'POST',
      headers: getHeaders(),
      body: JSON.stringify({
        author: `urn:li:person:${apiConfig.getKey('linkedin_person_id')}`,
        lifecycleState: 'PUBLISHED',
        specificContent: {
          'com.linkedin.ugc.ShareContent': {
            shareCommentary: { text },
            shareMediaCategory: 'IMAGE',
            media: [
              {
                status: 'READY',
                description: { text: 'Generated by AuraFrame' },
                media: asset,
                title: { text: 'AuraFrame Content' },
              },
            ],
          },
        },
        visibility: {
          'com.linkedin.ugc.MemberNetworkVisibility': visibility,
        },
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      return {
        success: false,
        error: error.message || `Error: ${response.status}`,
      };
    }

    const data = await response.json();
    return {
      success: true,
      postId: data.id,
      url: `https://www.linkedin.com/feed/update/${data.id}`,
    };
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Network error',
    };
  }
}

// OAuth flow helper - opens LinkedIn auth
export function getLinkedInAuthUrl(redirectUri: string): string {
  const clientId = apiConfig.getKey('linkedin_client_id');
  const scope = encodeURIComponent('w_member_social r_liteprofile r_emailaddress');
  const state = btoa(Date.now().toString());

  return (
    `https://www.linkedin.com/oauth/v2/authorization?` +
    `response_type=code&` +
    `client_id=${clientId}&` +
    `redirect_uri=${encodeURIComponent(redirectUri)}&` +
    `scope=${scope}&` +
    `state=${state}`
  );
}
